version: "3.8"

services:
  app:
    restart: on-failure
    image: bazario-app
    build: .
    env_file: ./.env
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url": "${POSTGRES_DB_URL}",
      "spring.datasource.username": "${POSTGRES_USER}",
      "spring.datasource.password": "${POSTGRES_ROOT_PASSWORD}",
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${DEBUG_PORT}"