server:
  servlet:
    context-path: /api
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB

spring:
  config:
    import:
      - optional:file:.env[.properties]
      - classpath:script-credentials.yaml

  application:
    name: bazario-backend

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  datasource:
    driver-class-name: org.postgresql.Driver
    #Cloud database
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_ROOT_PASSWORD}

#    #local
#    url: ${POSTGRES_LOCAL_DB_URL}
#    username: ${POSTGRES_LOCAL_USER}
#    password: ${POSTGRES_LOCAL_ROOT_PASSWORD}

  cache:
    type: redis

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    username: ${REDIS_USERNAME}
    password: ${REDIS_PASSWORD}
    ssl: true

  mail:
    host: ${MAILTRAP_HOST}
    port: ${MAILTRAP_PORT}
    username: ${MAILTRAP_USERNAME}
    password: ${MAILTRAP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: debug
jwt:
  expiration: ${JWT_EXPIRATION}
  secret: ${JWT_SECRET}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION}

aes:
  secret: ${AES_SECRET}

cookie:
  refresh:
    age: 604800 # 7 * 24 * 60 * 60

password:
  reset:
    code:
      length: 6

token:
  expiration:
    minutes: 15

verify:
  email:
    code:
      expiration:
        hours: 24
user:
  root:
    credentials:
      firstName: 'Vitalii'
      lastName: 'Stepanuk'
      avatar: 'https://happy-tails-mantine.vercel.app/_next/image?url=https%3A%2F%2Fimgur.com%2FtH5pXEV.png&w=1920&q=75'
      email: 'vitalii@ukr.net'
      phoneNumber: '+380982687965'
      password: 'rooT1#root'
      cityName: 'Lviv'
      cityCoordinate: '49.5017|24.0123'
  user:
    credentials:
      password: 'useR1#user'
bucket:
  global:
    tokens: 10
    duration: 60 #seconds
  limited-security:
    tokens: 1
    duration: 30 #seconds
  storage-period: 30 #minutes
cloudinary:
  name: ${CLOUDINARY_NAME}
  key: ${CLOUDINARY_KEY}
  secret: ${CLOUDINARY_SECRET}
image:
  min-num: 1
  max-num: 6
leader-board:
  max-size: 10
  trial-period: 1 #days
  count-delete-ad: 3
frontend:
  reset:
    password:
      url: https://bazario-marketplace-35cx.vercel.app/reset-password
  email:
    verification:
      url: https://bazario-marketplace-35cx.vercel.app/verify-email
